# Generated by Django 4.1 on 2022-09-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
